### ISSUE TITLE
Link per l'API AldoGiovanniGiacomo errato

### ISSUE THREAD

**Issue by JustOptimize** [giuseppebrb/giuseppebrb.github.io#1]
Ciao, l'href per il progetto `Aldo Giovanni Giacomo.API` contiene il link sbagliato.
Al momento e' `https://github.com/cobidev/react-simplefolio` al posto che `https://github.com/giuseppebrb/AldoGiovanniGiacomo.API`

**Comment by giuseppebrb** [comment]
Confermo il refuso; fiato con la commit 44f5329.
Thx 🍻
